### ISSUE TITLE
 get_order_history_crypto() only pulls last 75 transactions

### ISSUE THREAD

**Issue by Squirrel-hue** [JestonBlu/RobinHood#96]
As indicated in the title, get_order_history_crypto() is only pulling the last 75 transactions.  I tried on my RobinHood account, and I had a friend try on her account as well, and it was the same, only the last 75 transactions.

I am using the most up-to-date RobinHood package version from GitHub, and am using R 3.6.3 in RStudio Version 1.2.5033.

I am aware that this could be a problem with RobinHood API, and I will be reaching out to them soon. I did want to bring this to your attention and see if you (or others) were observed the same behavior.

Thank you for a great package.

**Comment by JestonBlu** [comment]
I dont have 75 transactions in crypto to reproduce this. The `api_orders()` function has a pager size to allow more results, but i dont see that coming through in the output of `api_order_crypto()`. Not sure if its the structure returned or if i just dont see it because i dont have that many transactions. If this is an issue for others we can reopen and ill give it some attention.
